[build-system]
requires = ["setuptools==58.2.0", "wheel"]

[tool.isort]
profile = "black"
multi_line_output = 3
src_paths = ["isort", "test"]
known_local_folder = ["aslprep"]
skip = ["aslprep/niworkflows", "aslprep/pybids", "aslprep/sdcflows", "aslprep/smriprep"]

[tool.black]
line-length = 99
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.github
    | \.hg
    | \.pytest_cache
    | _build
    | build
    | dist
  )/
  | versioneer.py
  | aslprep/_version.py
  | aslprep/niworkflows/
  | aslprep/pybids/
  | aslprep/sdcflows/
  | aslprep/smriprep/
)
'''

[tool.pytest.ini_options]
addopts = '-m "not examples_pcasl_singlepld_philips and not examples_pcasl_singlepld_siemens and not examples_pcasl_singlepld_ge and not examples_pcasl_multipld and not examples_pasl_multipld and not test_001 and not test_002 and not test_003"'
markers = [
    "examples_pasl_multipld: mark integration test",
    "examples_pcasl_multipld: mark integration test",
    "examples_pcasl_singlepld_ge: mark integration test",
    "examples_pcasl_singlepld_philips: mark integration test",
    "examples_pcasl_singlepld_siemens: mark integration test",
    "test_001: mark integration test for subject 01",
    "test_002: mark integration test for subject 10R01383",
    "test_003: mark integration test for subject A00086748",
]
