version: 2
jobs:
  build:
    environment:
      TZ: "/usr/share/zoneinfo/America/New_York"
      SCRATCH: "/scratch"
    docker:
      - image: docker:18.06.1-ce-git
    working_directory: /tmp/src/aslprep
    steps:
      - run:
          name: Install parallel gzip tar and python3
          command: |
            apk add --no-cache pigz tar python3
      - restore_cache:
          keys:
            - docker-v2-{{ .Branch }}-{{ epoch }}
            - docker-v2-{{ .Branch }}-
            - docker-v2-master-
            - docker-v2-
          paths:
            - /tmp/cache/docker.tar.gz
      - checkout
      - setup_remote_docker
      - run:
          name: Load Docker image layer cache
          no_output_timeout: 30m
          command: |
            docker info
            set +o pipefail
            if [ -f /tmp/cache/docker.tar.gz ]; then
              pigz -d --stdout /tmp/cache/docker.tar.gz | docker load
              docker images
            fi
      - run:
          name: Build Docker image
          no_output_timeout: 5h
          command: |
            # Get version, update files.
            THISVERSION=$( python3 get_version.py )
            if [[ ${THISVERSION:0:5} == "0" ]] ; then
              echo "WARNING: latest git tag could not be found"
              echo "Please, make sure you fetch all tags from upstream with"
              echo "the command ``git fetch --tags --verbose`` and push"
              echo "them to your fork with ``git push origin --tags``"
            fi
            sed -i "s/title = {aslprep}/title = {aslprep ${CIRCLE_TAG:-$THISVERSION}}/" aslprep/data/boilerplate.bib
            # Build docker image
            e=1 && for i in {1..5}; do
              docker build \
                --cache-from=pennlinc/aslprep \
                --rm=false \
                -t pennlinc/aslprep:latest . \
              && e=0 && break || sleep 15
            done && [ "$e" -eq "0" ]
      - run:
          name: Docker save
          no_output_timeout: 40m
          command: |
            mkdir -p /tmp/cache
            docker save  pennlinc/aslprep:latest \
            | pigz -8 -p 3 > /tmp/cache/docker.tar.gz
      - persist_to_workspace:
          root: /tmp
          paths:
            - cache/docker.tar.gz

  get_data:
    machine:
      image: circleci/classic:201711-01
    working_directory: /home/circleci/data
    steps:
      - restore_cache:
          keys:
            - data-v1-{{ epoch }}
            - data-v1-
      - run:
          name: Get test data and smriprep from box
          command: |
            mkdir -p /tmp/data
            cd /tmp/data
           
              wget --retry-connrefused --waitretry=5 --read-timeout=20 --timeout=15 -t 0 -q \
                -O downsampled.tar.xz "https://upenn.box.com/shared/static/og1ixccv5v8eir76emii6rrgnwu4thad.xz"
              tar xvfJ downsampled.tar.xz 
              rm -rf downsampled.tar.xz  
            
            
            cd /tmp/data
            if [[ ! -d /tmp/data/smriprep/sub-01  ]]; then
              wget --retry-connrefused --waitretry=5 --read-timeout=20 --timeout=15 -t 0 -q \
                -O smriprepx.tar.xz "https://upenn.box.com/shared/static/i64rbrpzfinpej0vct96mjw6ve7yycov.xz"
              tar xvfJ smriprepx.tar.xz 
              rm -rf smriprepx.tar.xz 
            else
              echo "smriprep data was cached"
            fi
            mkdir -p /tmp/wkdir


      - persist_to_workspace:
          root: /tmp
          paths:
            - data
      - save_cache:
         key: data-v1-{{ epoch }}
         paths:
            - /tmp/data


  update_cache:
    machine:
      image: circleci/classic:201711-01
    working_directory: /tmp/src/aslprep
    steps:
      - attach_workspace:
          at: /tmp
      - save_cache:
         key: docker-v2-{{ .Branch }}-{{ epoch }}
         paths:
           - /tmp/cache/docker.tar.gz


  aslprep_sub01:
    machine:
      image: circleci/classic:201711-01
    working_directory: /tmp/data
    steps:
      - checkout:
          path: /home/circleci/src/aslprep
      - run:
          name: Check whether build should be skipped
          command: |
            cd /home/circleci/src/aslprep
            if [[ "$( git log --format=oneline -n 1 $CIRCLE_SHA1 | grep -i -E '\[skip[ _]?aslprep_sub01\]' )" != "" ]]; then
              echo "Skipping aslprep_sub01 build"
              circleci step halt
            fi
      - attach_workspace:
          at: /tmp
      - restore_cache:
          keys:
            - aslprep_sub01-v2-{{ .Branch }}-{{ epoch }}
            - aslprep_sub01-v2-{{ .Branch }}
            - aslprep_sub01-v2-master
            - aslprep_sub01-v2-
      - run:
          name: Setting up test
          command: |
            mkdir -p /tmp/aslprep_ds && sudo setfacl -d -m group:$(id -gn):rwx /tmp/aslprep_ds  && sudo setfacl -m group:$(id -gn):rwx /tmp/aslprep_ds

      - run:
          name: Load Docker image layer cache
          no_output_timeout: 1h
          command: |
            docker info
            set +o pipefail
            if [ -f /tmp/cache/docker.tar.gz ]; then
              sudo apt update && sudo apt -y install pigz
              pigz -d --stdout /tmp/cache/docker.tar.gz | docker load
              docker images
            fi
      - run:
          name: get freesurfer licence
          no_output_timeout: 5m
          command: |
            cd /tmp 
            wget  https://upenn.box.com/shared/static/nlrtmp3vqif3t1q5v8yxpz9q4ow9mybj.txt
            mv nlrtmp3vqif3t1q5v8yxpz9q4ow9mybj.txt licence.txt 
      - run:
          name: Run full aslprep on aslprep_sub01 bold
          no_output_timeout: 5h
          command: |
            sudo setfacl -d -m group:$(id -gn):rwx /tmp/aslprep_ds && \
                sudo setfacl -m group:$(id -gn):rwx /tmp/aslprep_ds
        
            docker run --rm -it \
                -v /tmp/data:/data/ \
                -v /tmp/wkdir:/wkdir \
                -v /tmp:/scrth \
                -v /tmp/aslprep_ds/:/out \
                pennlinc/aslprep:latest \
                /data/testingbids  \
                /out  participant --participant-label 01 \
                -w /scrth/wkdir_sub01 --output-spaces asl \
                --fs-license-file /scrth/licence.txt \
                --scorescrub --basil --use-syn-sdc \
                --anat-derivatives /data/smriprep

      - run:
          name: Checking outputs of aslprep_sub01
          command: |
            cbfile=$(ls -f /tmp/aslprep_ds/aslprep/sub-01/perf/sub-01_desc-quality_control_cbf.csv)
            if [[ -f ${cbfile} ]]; then 
            echo "processing complete"
               exit 0
            else 
            echo "there is error "
                exit 1
            fi

      - run:
          name: Clean working directory
          when: always
          command: |
            sudo chown $(id -un):$(id -gn) -R /tmp/wkdir_sub01
            rm -rf /tmp/wkdir_sub01

      - store_artifacts:
          path: /tmp/aslprep_ds
          
  aslprep_subA00086748:
    machine:
      image: circleci/classic:201711-01
    working_directory: /tmp/data
    steps:
      - checkout:
          path: /home/circleci/src/aslprep
      - run:
          name: Check whether build should be skipped
          command: |
            cd /home/circleci/src/aslprep
            if [[ "$( git log --format=oneline -n 1 $CIRCLE_SHA1 | grep -i -E '\[skip[ _]?aslprep_subA00086748\]' )" != "" ]]; then
              echo "Skipping aslprep_subA00086748 build"
              circleci step halt
            fi
      - attach_workspace:
          at: /tmp
      - restore_cache:
          keys:
            - aslprep_subA00086748-v2-{{ .Branch }}-{{ epoch }}
            - aslprep_subA00086748-v2-{{ .Branch }}
            - aslprep_subA00086748-v2-master
            - aslprep_subA00086748-v2-
      - run:
          name: Setting up test
          command: |
            mkdir -p /tmp/aslprep_ds && sudo setfacl -d -m group:$(id -gn):rwx /tmp/aslprep_ds  && sudo setfacl -m group:$(id -gn):rwx /tmp/aslprep_ds

      - run:
          name: Load Docker image layer cache
          no_output_timeout: 1h
          command: |
            docker info
            set +o pipefail
            if [ -f /tmp/cache/docker.tar.gz ]; then
              sudo apt update && sudo apt -y install pigz
              pigz -d --stdout /tmp/cache/docker.tar.gz | docker load
              docker images
            fi
      - run:
          name: get freesurfer licence
          no_output_timeout: 5m
          command: |
            cd /tmp 
            wget  https://upenn.box.com/shared/static/nlrtmp3vqif3t1q5v8yxpz9q4ow9mybj.txt
            mv nlrtmp3vqif3t1q5v8yxpz9q4ow9mybj.txt licence.txt 
      - run:
          name: Run full aslprep on aslprep_ds bold
          no_output_timeout: 5h
          command: |
            sudo setfacl -d -m group:$(id -gn):rwx /tmp/aslprep_ds && \
                sudo setfacl -m group:$(id -gn):rwx /tmp/aslprep_ds
        

            docker run --rm -it \
                -v /tmp/data:/data/ \
                -v /tmp/wkdir:/wkdir \
                -v /tmp:/scrth \
                -v /tmp/aslprep_ds/:/out \
                pennlinc/aslprep:latest \
                /data/testingbids  \
                /out  participant --participant-label A00086748 \
                -w /scrth/wkdir_subA00086748 --output-spaces asl \
                --fs-license-file /scrth/licence.txt \
                --scorescrub --basil --use-syn-sdc \
                --anat-derivatives /data/smriprep

      - run:
          name: Checking outputs of aslprep_ds
          command: |
            cbfile=$(ls -f /tmp/aslprep_ds/aslprep/sub-A00086748/ses-BAS1/perf/sub-A00086748_ses-BAS1_desc-quality_control_cbf.csv)
            if [[ -f ${cbfile} ]]; then 
            echo "processing complete"
               exit 0
            else 
            echo "there is error "
                exit 1
            fi

      - run:
          name: Clean working directory
          when: always
          command: |
            sudo chown $(id -un):$(id -gn) -R /tmp/wkdir_subA00086748
            rm -rf /tmp/wkdir_subA00086748

      - store_artifacts:
          path: /tmp/aslprep_ds
  
  deploy_docker:
    machine:
      image: circleci/classic:201711-01
    working_directory: /tmp/src/aslprep
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Load Docker image layer cache
          no_output_timeout: 2h
          command: |
            docker info
            set +o pipefail
            if [ -f /tmp/cache/docker.tar.gz ]; then
              sudo apt update && sudo apt -y install pigz
              pigz -d --stdout /tmp/cache/docker.tar.gz | docker load
              docker images
            fi
      - run:
          name: Deploy to Docker Hub
          no_output_timeout: 1h
          command: |
            if [[ -n "$DOCKER_PASS" ]]; then
                docker login -u $DOCKER_USER -p $DOCKER_PASS
                docker tag pennlinc/aslprep pennlinc/aslprep:unstable
                docker push pennlinc/aslprep:unstable
            fi

            if [[ -n "$CIRCLE_TAG" ]]; then
                docker push pennlinc/aslprep:latest
                docker tag pennlinc/aslprep pennlinc/aslprep:$CIRCLE_TAG
                docker push pennlinc/aslprep:$CIRCLE_TAG
            fi

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

      - get_data:
          filters:
            branches:
              ignore:
                - /docs?\/.*/
                - /tests?\/.*/
            tags:
              only: /.*/

      - update_cache:
          requires:
            - build
          filters:
            branches:
              ignore:
                - /docs?\/.*/
                - /tests?\/.*/
            tags:
              only: /.*/

      - aslprep_sub01:
          requires:
            - get_data
            - build
          filters:
            branches:
              ignore:
                - /docs?\/.*/
                - /tests?\/.*/
            tags:
              only: /.*/
              
      - aslprep_subA00086748:
          requires:
            - get_data
            - build
          filters:
            branches:
              ignore:
                - /docs?\/.*/
                - /tests?\/.*/
            tags:
              only: /.*/

      - deploy_docker:
          requires:
            - build
            - aslprep_subA00086748
            - aslprep_sub01
          filters:
            branches:
              only: master
            tags:
              only: /.*/
