version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5

.dockersetup: &dockersetup
  docker:
    - image: pennlinc/aslprep_build:main
  working_directory: /src/aslprep

runinstall: &runinstall
  name: Install aslprep
  command: |
    VERSION=0+build
    if [[ -n "$CIRCLE_TAG" ]]; then
      VERSION="$CIRCLE_TAG"
    fi
    git checkout $CIRCLE_BRANCH
    echo "${VERSION}" > /src/aslprep/aslprep/VERSION
    echo "include aslprep/VERSION" >> /src/aslprep/MANIFEST.in
    pip install .[tests] --progress-bar off

    # Write the config file
    mkdir ~/.nipype
    CFG=~/.nipype/nipype.cfg
    printf "[execution]\nstop_on_first_crash = true\n" > ${CFG}
    echo "poll_sleep_duration = 0.01" >> ${CFG}
    echo "hash_method = content" >> ${CFG}

jobs:
  build:
    <<: *dockersetup
    steps:
      - checkout
      - run: *runinstall

  download_data_examples_pcasl_singlepld:
    <<: *dockersetup
    steps:
      - checkout
      - restore_cache:
          key: examples_pcasl_singlepld-v1
      - run:
          name: Get test data and smriprep from box
          command: |
            cd /src/aslprep/.circleci
            python get_data.py ${PWD}/data downsampled
      - save_cache:
          key: examples_pcasl_singlepld-v1
          paths:
              - /src/aslprep/.circleci/data

  download_data_examples_pcasl_multipld:
    <<: *dockersetup
    steps:
      - checkout
      - restore_cache:
          key: examples_pcasl_multipld-v1
      - run:
          name: Get test data and smriprep from box
          command: |
            cd /src/aslprep/.circleci
            python get_data.py ${PWD}/data downsampled
      - save_cache:
          key: examples_pcasl_multipld-v1
          paths:
              - /src/aslprep/.circleci/data

  download_data_examples_pasl_multipld:
    <<: *dockersetup
    steps:
      - checkout
      - restore_cache:
          key: examples_pasl_multipld-v1
      - run:
          name: Get test data and smriprep from box
          command: |
            cd /src/aslprep/.circleci
            python get_data.py ${PWD}/data downsampled
      - save_cache:
          key: examples_pasl_multipld-v1
          paths:
              - /src/aslprep/.circleci/data

  download_data_test_001:
    <<: *dockersetup
    steps:
      - checkout
      - restore_cache:
          key: test_001-v1
      - run:
          name: Get test data and smriprep from box
          command: |
            cd /src/aslprep/.circleci
            python get_data.py ${PWD}/data downsampled
      - save_cache:
          key: test_001-v1
          paths:
              - /src/aslprep/.circleci/data

  download_data_test_002:
    <<: *dockersetup
    steps:
      - checkout
      - restore_cache:
          key: test_002-v1
      - run:
          name: Get test data and smriprep from box
          command: |
            cd /src/aslprep/.circleci
            python get_data.py ${PWD}/data downsampled
      - save_cache:
          key: test_002-v1
          paths:
              - /src/aslprep/.circleci/data

  download_data_test_003:
    <<: *dockersetup
    steps:
      - checkout
      - restore_cache:
          key: test_003-v1
      - run:
          name: Get test data and smriprep from box
          command: |
            cd /src/aslprep/.circleci
            python get_data.py ${PWD}/data downsampled
      - save_cache:
          key: test_003-v1
          paths:
              - /src/aslprep/.circleci/data

  aslprep_examples_pcasl_singlepld:
    <<: *dockersetup
    steps:
      - checkout
      - run:
          name: Check whether build should be skipped
          command: |
            cd /src/aslprep
            if [[ "$( git log --format=oneline -n 1 $CIRCLE_SHA1 | grep -i -E '\[skip[ _]?examples_pcasl_singlepld\]' )" != "" ]]; then
              echo "Skipping examples_pcasl_singlepld build"
              circleci step halt
            fi
      - restore_cache:
          key: examples_pcasl_singlepld-v1
      - run: *runinstall
      - run:
          name: Run full aslprep on examples_pcasl_singlepld dataset
          no_output_timeout: 5h
          command: |
            pytest -rP -o log_cli=true -m "examples_pcasl_singlepld" --cov-append --cov-report term-missing --cov=aslprep --data_dir=/src/aslprep/.circleci/data --output_dir=/src/aslprep/.circleci/out --working_dir=/src/aslprep/.circleci/work aslprep
            mkdir /src/coverage
            mv /src/aslprep/.coverage /src/coverage/.coverage.examples_pcasl_singlepld
      - store_artifacts:
          path: /src/aslprep/.circleci/out
      - persist_to_workspace:
          root: /src/coverage
          paths:
              - .coverage.examples_pcasl_singlepld

  aslprep_examples_pcasl_multipld:
    <<: *dockersetup
    steps:
      - checkout
      - run:
          name: Check whether build should be skipped
          command: |
            cd /src/aslprep
            if [[ "$( git log --format=oneline -n 1 $CIRCLE_SHA1 | grep -i -E '\[skip[ _]?examples_pcasl_multipld\]' )" != "" ]]; then
              echo "Skipping examples_pcasl_multipld build"
              circleci step halt
            fi
      - restore_cache:
          key: examples_pcasl_multipld-v1
      - run: *runinstall
      - run:
          name: Run full aslprep on examples_pcasl_multipld dataset
          no_output_timeout: 5h
          command: |
            pytest -rP -o log_cli=true -m "examples_pcasl_multipld" --cov-append --cov-report term-missing --cov=aslprep --data_dir=/src/aslprep/.circleci/data --output_dir=/src/aslprep/.circleci/out --working_dir=/src/aslprep/.circleci/work aslprep
            mkdir /src/coverage
            mv /src/aslprep/.coverage /src/coverage/.coverage.examples_pcasl_multipld
      - store_artifacts:
          path: /src/aslprep/.circleci/out
      - persist_to_workspace:
          root: /src/coverage
          paths:
              - .coverage.examples_pcasl_multipld

  aslprep_examples_pasl_multipld:
    <<: *dockersetup
    steps:
      - checkout
      - run:
          name: Check whether build should be skipped
          command: |
            cd /src/aslprep
            if [[ "$( git log --format=oneline -n 1 $CIRCLE_SHA1 | grep -i -E '\[skip[ _]?examples_pasl_multipld\]' )" != "" ]]; then
              echo "Skipping examples_pasl_multipld build"
              circleci step halt
            fi
      - restore_cache:
          key: examples_pasl_multipld-v1
      - run: *runinstall
      - run:
          name: Run full aslprep on examples_pasl_multipld dataset
          no_output_timeout: 5h
          command: |
            pytest -rP -o log_cli=true -m "examples_pasl_multipld" --cov-append --cov-report term-missing --cov=aslprep --data_dir=/src/aslprep/.circleci/data --output_dir=/src/aslprep/.circleci/out --working_dir=/src/aslprep/.circleci/work aslprep
            mkdir /src/coverage
            mv /src/aslprep/.coverage /src/coverage/.coverage.examples_pasl_multipld
      - store_artifacts:
          path: /src/aslprep/.circleci/out
      - persist_to_workspace:
          root: /src/coverage
          paths:
              - .coverage.examples_pasl_multipld

  aslprep_test_001:
    <<: *dockersetup
    steps:
      - checkout
      - run:
          name: Check whether build should be skipped
          command: |
            cd /src/aslprep
            if [[ "$( git log --format=oneline -n 1 $CIRCLE_SHA1 | grep -i -E '\[skip[ _]?test_001\]' )" != "" ]]; then
              echo "Skipping test_001 build"
              circleci step halt
            fi
      - restore_cache:
          key: test_001-v1
      - run: *runinstall
      - run:
          name: Run full aslprep on test_001 dataset
          no_output_timeout: 5h
          command: |
            pytest -rP -o log_cli=true -m "test_001" --cov-append --cov-report term-missing --cov=aslprep --data_dir=/src/aslprep/.circleci/data --output_dir=/src/aslprep/.circleci/out --working_dir=/src/aslprep/.circleci/work aslprep
            mkdir /src/coverage
            mv /src/aslprep/.coverage /src/coverage/.coverage.test_001
      - store_artifacts:
          path: /src/aslprep/.circleci/out
      - persist_to_workspace:
          root: /src/coverage
          paths:
              - .coverage.test_001

  aslprep_test_002:
    <<: *dockersetup
    steps:
      - checkout
      - run:
          name: Check whether build should be skipped
          command: |
            cd /src/aslprep
            if [[ "$( git log --format=oneline -n 1 $CIRCLE_SHA1 | grep -i -E '\[skip[ _]?test_002\]' )" != "" ]]; then
              echo "Skipping test_002 build"
              circleci step halt
            fi
      - restore_cache:
          key: test_002-v1
      - run: *runinstall
      - run:
          name: Run full aslprep on test_002 dataset
          no_output_timeout: 5h
          command: |
            pytest -rP -o log_cli=true -m "test_002" --cov-append --cov-report term-missing --cov=aslprep --data_dir=/src/aslprep/.circleci/data --output_dir=/src/aslprep/.circleci/out --working_dir=/src/aslprep/.circleci/work aslprep
            mkdir /src/coverage
            mv /src/aslprep/.coverage /src/coverage/.coverage.test_002
      - store_artifacts:
          path: /src/aslprep/.circleci/out
      - persist_to_workspace:
          root: /src/coverage
          paths:
              - .coverage.test_002

  aslprep_test_003:
    <<: *dockersetup
    steps:
      - checkout
      - run:
          name: Check whether build should be skipped
          command: |
            cd /src/aslprep
            if [[ "$( git log --format=oneline -n 1 $CIRCLE_SHA1 | grep -i -E '\[skip[ _]?aslprep_test_003\]' )" != "" ]]; then
              echo "Skipping aslprep_test_003 build"
              circleci step halt
            fi
      - restore_cache:
          key: test_003-v1
      - run: *runinstall
      - run:
          name: Run full aslprep on test_003 dataset
          no_output_timeout: 5h
          command: |
            pytest -rP -o log_cli=true -m "test_003" --cov-append --cov-report term-missing --cov=aslprep --data_dir=/src/aslprep/.circleci/data --output_dir=/src/aslprep/.circleci/out --working_dir=/src/aslprep/.circleci/work aslprep
            mkdir /src/coverage
            mv /src/aslprep/.coverage /src/coverage/.coverage.test_003
      - store_artifacts:
          path: /src/aslprep/.circleci/out
      - persist_to_workspace:
          root: /src/coverage
          paths:
              - .coverage.test_003

  pytests:
    <<: *dockersetup
    steps:
      - checkout
      - run:
          name: Check whether build should be skipped
          command: |
            cd /src/aslprep
            if [[ "$( git log --format=oneline -n 1 $CIRCLE_SHA1 | grep -i -E '\[skip[ _]?pytests\]' )" != "" ]]; then
              echo "Skipping pytests build"
              circleci step halt
            fi
      - restore_cache:
          key: data-v4
      - run: *runinstall
      - run:
          name: Run pytest on the tests directory
          no_output_timeout: 1h
          command: |
            pytest --cov-append --cov-report term-missing --cov=aslprep --data_dir=/src/aslprep/.circleci/data --output_dir=/src/aslprep/.circleci/out --working_dir=/src/aslprep/.circleci/work aslprep/tests
            mkdir /src/coverage
            mv /src/aslprep/.coverage /src/coverage/.coverage.pytests
      - persist_to_workspace:
          root: /src/coverage
          paths:
              - .coverage.pytests
      - store_artifacts:
          path: /src/aslprep/.circleci/out/

  merge_coverage:
    <<: *dockersetup
    steps:
      - checkout
      - attach_workspace:
          at: /src/coverage
      - run: *runinstall
      - run:
          name: Merge coverage files
          command: |
            cd /src/coverage/
            coverage combine
            coverage xml
      - store_artifacts:
          path: /src/coverage
      - codecov/upload:
          file: /src/coverage/coverage.xml

  deployable:
    docker:
      - image: busybox:latest
    steps:
      - run: echo Deploying!

  build_and_deploy:
    environment:
      TZ: "/usr/share/zoneinfo/America/New_York"
    docker:
      - image: cimg/base:2020.09
    working_directory: /tmp/src/aslprep_build
    steps:
      - checkout
      - setup_remote_docker:
         version: 19.03.13
         docker_layer_caching: true
      - run:
          name: Build Docker image
          no_output_timeout: 3h
          command: |
            # Get version, update files.
            THISVERSION=$( python3 get_version.py )
            if [[ ${THISVERSION:0:1} == "0" ]] ; then
              echo "WARNING: latest git tag could not be found"
              echo "Please, make sure you fetch all tags from upstream with"
              echo "the command ``git fetch --tags --verbose`` and push"
              echo "them to your fork with ``git push origin --tags``"
            fi
            sed -i "s/title = {aslprep}/title = {aslprep ${CIRCLE_TAG:-$THISVERSION}}/" aslprep/data/boilerplate.bib
            # Build docker image
            e=1 && for i in {1..5}; do
              docker build \
                --cache-from=pennlinc/aslprep \
                --rm=false \
                -t pennlinc/aslprep:latest \
                --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
                --build-arg VCS_REF=`git rev-parse --short HEAD` \
                --build-arg VERSION="${CIRCLE_TAG:-$THISVERSION}" . \
              && e=0 && break || sleep 15
            done && [ "$e" -eq "0" ]
      - run:
          name: Deploy to Docker Hub
          no_output_timeout: 40m
          command: |
            if [[ -n "$DOCKERHUB_TOKEN" ]]; then
              docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
              docker tag pennlinc/aslprep pennlinc/aslprep:unstable
              docker push pennlinc/aslprep:unstable
              if [[ -n "$CIRCLE_TAG" ]]; then
                docker push pennlinc/aslprep:latest
                docker tag pennlinc/aslprep pennlinc/aslprep:$CIRCLE_TAG
                docker push pennlinc/aslprep:$CIRCLE_TAG
              fi
            fi

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

      - download_data_examples_pcasl_singlepld:
          filters:
            branches:
              ignore:
                - /docs?\/.*/
                - /tests?\/.*/
            tags:
              only: /.*/

      - download_data_examples_pcasl_multipld:
          filters:
            branches:
              ignore:
                - /docs?\/.*/
                - /tests?\/.*/
            tags:
              only: /.*/

      - download_data_examples_pasl_multipld:
          filters:
            branches:
              ignore:
                - /docs?\/.*/
                - /tests?\/.*/
            tags:
              only: /.*/

      - download_data_test_001:
          filters:
            branches:
              ignore:
                - /docs?\/.*/
                - /tests?\/.*/
            tags:
              only: /.*/

      - download_data_test_002:
          filters:
            branches:
              ignore:
                - /docs?\/.*/
                - /tests?\/.*/
            tags:
              only: /.*/

      - download_data_test_003:
          filters:
            branches:
              ignore:
                - /docs?\/.*/
                - /tests?\/.*/
            tags:
              only: /.*/

      - aslprep_examples_pcasl_singlepld:
          requires:
            - download_data_examples_pcasl_singlepld
            - build
          filters:
            branches:
              ignore:
                - /docs?\/.*/
                - /tests?\/.*/
            tags:
              only: /.*/

      - aslprep_examples_pcasl_multipld:
          requires:
            - download_data_examples_pcasl_multipld
            - build
          filters:
            branches:
              ignore:
                - /docs?\/.*/
                - /tests?\/.*/
            tags:
              only: /.*/

      - aslprep_examples_pasl_multipld:
          requires:
            - download_data_examples_pasl_multipld
            - build
          filters:
            branches:
              ignore:
                - /docs?\/.*/
                - /tests?\/.*/
            tags:
              only: /.*/

      - aslprep_test_001:
          requires:
            - download_data_test_001
            - build
          filters:
            branches:
              ignore:
                - /docs?\/.*/
                - /tests?\/.*/
            tags:
              only: /.*/

      - aslprep_test_002:
          requires:
            - download_data_test_002
            - build
          filters:
            branches:
              ignore:
                - /docs?\/.*/
                - /tests?\/.*/
            tags:
              only: /.*/

      - aslprep_test_003:
          requires:
            - download_data_test_003
            - build
          filters:
            branches:
              ignore:
                - /docs?\/.*/
                - /tests?\/.*/
            tags:
              only: /.*/

      - pytests:
          requires:
            - download_data_test_001
            - download_data_test_002
            - download_data_test_003
            - build
          filters:
            branches:
              ignore:
                - /docs?\/.*/
                - /tests?\/.*/
            tags:
              only: /.*/

      - merge_coverage:
          requires:
            - aslprep_examples_pcasl_singlepld
            - aslprep_examples_pcasl_multipld
            - aslprep_examples_pasl_multipld
            - aslprep_test_001
            - aslprep_test_002
            - aslprep_test_003
            - pytests
          filters:
            branches:
              ignore:
                - /docs?\/.*/
                - /tests?\/.*/
            tags:
              only: /.*/

      - deployable:
          requires:
            - build
            - aslprep_examples_pcasl_singlepld
            - aslprep_examples_pcasl_multipld
            - aslprep_examples_pasl_multipld
            - aslprep_test_001
            - aslprep_test_002
            - aslprep_test_003
          filters:
            branches:
              only: main
            tags:
              only: /.*/

      - build_and_deploy:
          requires:
            - deployable
          filters:
            branches:
              only: main
            tags:
              only: /.*/
