"""Simulated ASL fixtures with ground truth, generated by aslscan.

This module is the registry for the ground-truth test datasets described in
``docs/specs/2026-10-08-aslscan-ground-truth-tests-design.md``.
It pins the simulator and every input,
renders the spec file that keys the CircleCI cache (``.circleci/aslscan_fixtures.txt``),
and generates, verifies and locates the fixtures.

It must import with the standard library alone,
so that ``python -m aslprep.tests.aslscan_fixtures --spec`` runs anywhere.
Third-party imports live inside the functions that need them.

Usage::

    python -m aslprep.tests.aslscan_fixtures --spec > .circleci/aslscan_fixtures.txt
"""

import argparse
import contextlib
import hashlib
import json
import math
import os
import re
import shutil
import subprocess
import sys
import tomllib
from pathlib import Path

#: Bump to discard a bad CircleCI cache entry (caches are immutable).
CACHE_EPOCH = 1

ASLSCAN_REPO = 'https://github.com/PennLINC/aslscan.git'
ASLSCAN_REF = '82919454d11ee63a1bc8032e4a362f9b745e5d97'
MRSIM_ACQ_REPO = 'https://github.com/PennLINC/mrsim-acq.git'
MRSIM_ACQ_REF = 'e64caff8b18358704ef876b5a16a344192b3a014'
RUST_TOOLCHAIN = '1.98.0'
CARGO_FEATURES = 'cli,kspace,par'

#: Python requirements of the fixture generator (CI installs these into a venv).
PY_REQUIREMENTS = (
    'numpy==2.5.3',
    'nibabel==5.4.2',
    'scipy==1.18.1',
    'templateflow==25.1.2',
)

#: TemplateFlow files the phantoms are built from: (query, file name, SHA-256).
TEMPLATE = 'MNI152NLin2009cAsym'
TEMPLATES = (
    (
        {'resolution': 1, 'desc': None, 'suffix': 'T1w'},
        'tpl-MNI152NLin2009cAsym_res-01_T1w.nii.gz',
        '1f27aabea9f7183dc0c69dafa71e1787b921ca778d655d9c1bf302b273d5627a',
    ),
    (
        {'resolution': 1, 'desc': 'brain', 'suffix': 'mask'},
        'tpl-MNI152NLin2009cAsym_res-01_desc-brain_mask.nii.gz',
        'e40bb1816736504d4c25abc243c1c8503df1d308f64c048318aa4b829e09a7ae',
    ),
    (
        {'resolution': 1, 'label': 'GM', 'suffix': 'probseg'},
        'tpl-MNI152NLin2009cAsym_res-01_label-GM_probseg.nii.gz',
        '662b18e83dddc554b19c621d9750af3454b54d4e103df03633eacced3884805a',
    ),
    (
        {'resolution': 1, 'label': 'WM', 'suffix': 'probseg'},
        'tpl-MNI152NLin2009cAsym_res-01_label-WM_probseg.nii.gz',
        'b2f80e29f5a1ef55325215d1716ef611f5b1a3cd97b4a49ef4e9564e9564e945',
    ),
    (
        {'resolution': 1, 'label': 'CSF', 'suffix': 'probseg'},
        'tpl-MNI152NLin2009cAsym_res-01_label-CSF_probseg.nii.gz',
        '8a74e36b067a3fb670f6785b94479cc3df4d219a3f72d69d57aef332e4947048',
    ),
)

#: Modules (in this directory) whose source feeds the spec digest.
HASHED_MODULES = ('aslscan_fixtures.py', 'truth_geometry.py')

#: Per-label constants of ASLDRO's hrgt_icbm_2009a_nls_3t, used by the TemplateFlow phantoms.
#: This is a new phantom that shares ASLDRO's constants, not its anatomy.
TISSUES = {
    1: {
        'name': 'grey_matter',
        'perfusion': 60.0,
        'att': 0.8,
        'T1map': 1.33,
        'T2map': 0.080,
        'T2starmap': 0.066,
        'M0map': 74.6219,
    },
    2: {
        'name': 'white_matter',
        'perfusion': 20.0,
        'att': 1.2,
        'T1map': 0.83,
        'T2map': 0.110,
        'T2starmap': 0.053,
        'M0map': 64.7239,
    },
    3: {
        'name': 'csf',
        'perfusion': 0.0,
        'att': 1000.0,
        'T1map': 3.0,
        'T2map': 0.300,
        'T2starmap': 0.200,
        'M0map': 68.0456,
    },
}

#: The phantom contract aslscan's loader enforces (src/phantom.rs): map name -> Units.
PHANTOM_MAPS = {
    'perfusion': 'ml/100g/min',
    'att': 's',
    'T1map': 's',
    'T2map': 's',
    'T2starmap': 's',
    'M0map': 'arbitrary',
}
OPTIONAL_PHANTOM_MAPS = {'abv': 'fraction', 'aatt': 's'}

#: Phantom name -> builder parameters (Section 4.2 of the spec).
#: ``modulation`` multiplies a map by ``1 + amplitude * prod_i cos(2 pi x_i / period_i + phase_i)``
#: inside tissue (world mm), so the truth varies within tissue.
PHANTOM_PARAMS = {
    'tfmni': {
        'source': 'templateflow',
        'template': TEMPLATE,
        'probability_floor': 0.3,
        'tissues': TISSUES,
        'kinetics': {'LambdaBloodBrain': 0.9, 'T1ArterialBlood': 1.65, 'MagneticFieldStrength': 3},
        'modulation': {
            'perfusion': {
                'amplitude': 0.2,
                'periods_mm': [120.0, 140.0, 100.0],
                'phases': [0.3, 1.1, 2.0],
            },
            'att': {
                'amplitude': 0.15,
                'periods_mm': [90.0, 110.0, 130.0],
                'phases': [1.7, 0.4, 2.6],
            },
        },
    },
    'tfmni-flat': {
        'source': 'templateflow',
        'template': TEMPLATE,
        'probability_floor': 0.3,
        'tissues': TISSUES,
        'kinetics': {'LambdaBloodBrain': 0.9, 'T1ArterialBlood': 1.65, 'MagneticFieldStrength': 3},
        'modulation': {},
    },
}

#: Recipe name -> one-line description. Inputs live in tests/data/aslscan/<name>/.
RECIPES = {
    # Fast tier: cropped phantom, noise-free, no anatomy (spec Section 5).
    'fast_pcasl_seq': 'PCASL, single delay, ascending slices, separate M0',
    'fast_pcasl_rev': 'PCASL with SliceEncodingDirection k-',
    'fast_pcasl_mb': 'PCASL with multiband 2',
    'fast_pasl_q2tips': 'PASL, single TI, Q2TIPS',
    'fast_pasl_quipss2': 'PASL, single TI, QUIPSS II',
    'fast_m0_included': 'PCASL with an M0 volume in the series',
    'fast_m0_estimate': 'PCASL calibrated with M0Estimate',
    'fast_m0_absent': 'PCASL calibrated with the mean control',
    'fast_m0_shorttr': 'PCASL with a separate M0 at TR 3 s',
    'fast_label_first': 'PCASL with label-control ordering',
    'fast_deltam': 'PCASL as delta-M volumes',
    'fast_bs_le_absent': 'PCASL with two suppression pulses and no LabelingEfficiency',
}

TESTS_DIR = Path(__file__).resolve().parent
RECIPES_DIR = TESTS_DIR / 'data' / 'aslscan'
#: aslscan does not commit a Cargo.lock, so the build uses this one (with --locked).
CARGO_LOCK = TESTS_DIR / 'data' / 'aslscan-Cargo.lock'
REPO_ROOT = TESTS_DIR.parents[1]
SPEC_FILE = REPO_ROOT / '.circleci' / 'aslscan_fixtures.txt'
SPEC_COMMAND = 'python -m aslprep.tests.aslscan_fixtures --spec > .circleci/aslscan_fixtures.txt'


def _lf(data):
    """Normalize line endings so Windows and POSIX checkouts hash alike."""
    return data.replace(b'\r\n', b'\n')


def _digest_bytes(data):
    return hashlib.sha256(_lf(data)).hexdigest()


def _digest_dir(path):
    """Hash a directory's files: sorted relative path, length and LF-normalized content."""
    path = Path(path)
    sha = hashlib.sha256()
    for f in sorted(p for p in path.rglob('*') if p.is_file()):
        data = _lf(f.read_bytes())
        sha.update(f.relative_to(path).as_posix().encode())
        sha.update(b'\0')
        sha.update(str(len(data)).encode())
        sha.update(b'\0')
        sha.update(data)
    return sha.hexdigest()


def _digest_json(obj):
    return hashlib.sha256(json.dumps(obj, sort_keys=True).encode()).hexdigest()


def spec_text():
    """Render the spec file: every input that determines the fixtures, then their digest."""
    lines = [
        '# generated by python -m aslprep.tests.aslscan_fixtures --spec; do not edit',
        f'CACHE_EPOCH={CACHE_EPOCH}',
        f'ASLSCAN_REF={ASLSCAN_REF}',
        f'MRSIM_ACQ_REF={MRSIM_ACQ_REF}',
        f'RUST_TOOLCHAIN={RUST_TOOLCHAIN}',
        f'CARGO_FEATURES={CARGO_FEATURES}',
        f'CARGO_LOCK={_digest_bytes(CARGO_LOCK.read_bytes())}',
        f'PY_REQUIREMENTS={";".join(PY_REQUIREMENTS)}',
    ]
    lines += [f'TEMPLATE {name} {sha}' for _, name, sha in TEMPLATES]
    lines += [
        f'BUILDER {mod} {_digest_bytes((TESTS_DIR / mod).read_bytes())}' for mod in HASHED_MODULES
    ]
    lines += [f'PHANTOM {name} {_digest_json(p)}' for name, p in sorted(PHANTOM_PARAMS.items())]
    lines += [f'RECIPE {name} {_digest_dir(RECIPES_DIR / name)}' for name in sorted(RECIPES)]
    digest = hashlib.sha256('\n'.join(lines).encode()).hexdigest()
    return '\n'.join([*lines, f'DIGEST {digest}']) + '\n'


def spec_digest():
    """The DIGEST line of the current spec text."""
    return spec_text().rstrip('\n').rsplit(' ', 1)[1]


# ---------------------------------------------------------------------------------------------
# The simulator
# ---------------------------------------------------------------------------------------------
STAMP_NAME = 'aslscan.build.json'


class AslscanUnavailable(RuntimeError):
    """No aslscan binary built at the pinned revisions could be found."""


def _sha256_file(path):
    sha = hashlib.sha256()
    with open(path, 'rb') as f:
        for block in iter(lambda: f.read(1 << 20), b''):
            sha.update(block)
    return sha.hexdigest()


def _expected_stamp():
    return {
        'aslscan': ASLSCAN_REF,
        'mrsim-acq': MRSIM_ACQ_REF,
        'toolchain': RUST_TOOLCHAIN,
        'features': CARGO_FEATURES,
        'cargo_lock': _digest_bytes(CARGO_LOCK.read_bytes()),
    }


def _tool(name):
    """Absolute path of an executable on PATH."""
    path = shutil.which(name)
    if path is None:
        raise FileNotFoundError(f'{name} is required but was not found on PATH')
    return path


def _checkout(repo, ref, dest):
    """Clone (or reuse) ``repo`` at ``dest`` and detach at ``ref``, verifying the result."""
    git = _tool('git')
    if not (dest / '.git').is_dir():
        subprocess.run([git, 'clone', '--quiet', repo, str(dest)], check=True)
    subprocess.run([git, '-C', str(dest), 'fetch', '--quiet', 'origin', ref], check=True)
    subprocess.run([git, '-C', str(dest), 'checkout', '--quiet', '--detach', ref], check=True)
    head = subprocess.run(
        [git, '-C', str(dest), 'rev-parse', 'HEAD'], check=True, capture_output=True, text=True
    ).stdout.strip()
    if head != ref:
        raise RuntimeError(f'{dest}: HEAD is {head}, expected {ref}')


def build_aslscan(workdir):
    """Build aslscan at the pinned revisions and return the binary's path.

    The two crates are cloned side by side, because aslscan finds mrsim-acq at
    ``../mrsim-acq``. A stamp written next to the binary records what it was built from;
    :func:`find_aslscan` accepts only stamped binaries, since ``aslscan --version`` does not
    report a revision. The path is also written to ``<workdir>/BIN`` for CI steps.
    """
    workdir = Path(workdir).resolve()
    workdir.mkdir(parents=True, exist_ok=True)
    _checkout(MRSIM_ACQ_REPO, MRSIM_ACQ_REF, workdir / 'mrsim-acq')
    _checkout(ASLSCAN_REPO, ASLSCAN_REF, workdir / 'aslscan')
    shutil.copyfile(CARGO_LOCK, workdir / 'aslscan' / 'Cargo.lock')
    env = {**os.environ, 'CARGO_TARGET_DIR': str(workdir / 'target')}
    subprocess.run(
        [
            _tool('cargo'),
            f'+{RUST_TOOLCHAIN}',
            'build',
            '--release',
            '--locked',
            '--features',
            CARGO_FEATURES,
            '--bin',
            'aslscan',
        ],
        cwd=workdir / 'aslscan',
        env=env,
        check=True,
    )
    binary = workdir / 'target' / 'release' / 'aslscan'
    stamp = {**_expected_stamp(), 'sha256': _sha256_file(binary)}
    (binary.parent / STAMP_NAME).write_text(json.dumps(stamp, indent=2) + '\n')
    (workdir / 'BIN').write_text(f'{binary}\n')
    return binary


def check_aslscan(binary):
    """Raise :class:`AslscanUnavailable` unless ``binary`` carries a matching stamp."""
    binary = Path(binary)
    stamp_file = binary.parent / STAMP_NAME
    if not binary.is_file():
        raise AslscanUnavailable(f'{binary} does not exist')
    if not stamp_file.is_file():
        raise AslscanUnavailable(
            f'{binary} has no {STAMP_NAME}; build it at the pinned revisions with '
            '`python -m aslprep.tests.aslscan_fixtures --build-aslscan <dir>`'
        )
    stamp = json.loads(stamp_file.read_text())
    expected = _expected_stamp()
    wrong = {k: stamp.get(k) for k, v in expected.items() if stamp.get(k) != v}
    if wrong:
        raise AslscanUnavailable(f'{binary} was built from {wrong}, expected {expected}')
    if stamp.get('sha256') != _sha256_file(binary):
        raise AslscanUnavailable(f'{binary} does not match the hash in its {STAMP_NAME}')
    return binary


def find_aslscan(explicit=None):
    """Locate a stamped aslscan: ``explicit``, then ``$ASLSCAN``, then ``PATH``."""
    candidates = [explicit, os.environ.get('ASLSCAN'), shutil.which('aslscan')]
    errors = []
    for candidate in filter(None, candidates):
        try:
            return check_aslscan(candidate)
        except AslscanUnavailable as exc:
            errors.append(str(exc))
    raise AslscanUnavailable(
        'no aslscan built at the pinned revisions was found'
        + (': ' + '; '.join(errors) if errors else ' (set $ASLSCAN or put aslscan on PATH)')
    )


# ---------------------------------------------------------------------------------------------
# Phantoms
# ---------------------------------------------------------------------------------------------
class PhantomContractError(ValueError):
    """A phantom directory does not satisfy aslscan's loader contract."""


def _write_json(path, obj):
    Path(path).write_text(json.dumps(obj, indent=2, sort_keys=True) + '\n')


def _phantom_dir(name, data_dir):
    safe = name.replace(':', '_').replace(',', '-')
    return Path(data_dir) / 'aslscan' / '_phantoms' / safe


def phantom_digest(name):
    """Digest of everything that determines a phantom (crops include their base's digest)."""
    if name.startswith('crop:'):
        _, base, ranges = name.split(':', 2)
        return _digest_json({'crop': ranges, 'base': phantom_digest(base)})
    if name.startswith('subject:'):
        return _digest_json({'subject': name})
    if name not in PHANTOM_PARAMS:
        raise KeyError(f'unknown phantom {name!r}; known: {sorted(PHANTOM_PARAMS)}')
    return _digest_json(
        {
            'params': PHANTOM_PARAMS[name],
            'templates': [t[2] for t in TEMPLATES],
            'builder': _digest_bytes((TESTS_DIR / 'aslscan_fixtures.py').read_bytes()),
        }
    )


def fetch_templates():
    """Download the pinned TemplateFlow files and verify their checksums."""
    import templateflow.api as tflow

    paths = {}
    for query, name, sha in TEMPLATES:
        path = Path(tflow.get(TEMPLATE, **query))
        if path.name != name:
            raise RuntimeError(f'TemplateFlow returned {path.name} for {query}, expected {name}')
        actual = _sha256_file(path)
        if actual != sha:
            raise RuntimeError(f'{path} has SHA-256 {actual}, expected {sha} (template drift?)')
        paths[name] = path
    return paths


def modulation_field(params, affine, shape):
    """``1 + a * prod_i cos(2 pi x_i / P_i + phi_i)`` on a grid's voxel centres (world mm)."""
    import numpy as np

    ijk = np.indices(shape, dtype=np.float64)
    world = np.tensordot(affine[:3, :3], ijk, axes=1) + affine[:3, 3, None, None, None]
    field = np.ones(shape)
    for axis in range(3):
        period = params['periods_mm'][axis]
        field = field * np.cos(2 * np.pi * world[axis] / period + params['phases'][axis])
    return 1 + params['amplitude'] * field


def _build_templateflow_phantom(params, out):
    import nibabel as nb
    import numpy as np

    paths = fetch_templates()

    def load(label):
        return nb.load(paths[f'tpl-{TEMPLATE}_res-01_{label}.nii.gz'])

    mask_img = load('desc-brain_mask')
    affine = mask_img.affine
    mask = np.asanyarray(mask_img.dataobj) > 0
    probs = np.stack(
        [np.asanyarray(load(f'label-{t}_probseg').dataobj) for t in ('GM', 'WM', 'CSF')], axis=-1
    ).astype(np.float32)
    labels = (np.argmax(probs, axis=-1) + 1).astype(np.int16)
    labels[(probs.max(axis=-1) < params['probability_floor']) | ~mask] = 0

    for quantity, units in PHANTOM_MAPS.items():
        data = np.zeros(labels.shape, np.float32)
        for value, tissue in params['tissues'].items():
            data[labels == int(value)] = tissue[quantity]
        mod = params['modulation'].get(quantity)
        if mod:
            field = modulation_field(mod, affine, labels.shape).astype(np.float32)
            # CSF stays unperfused and its ATT stays the "never arrives" sentinel
            tissue = (labels == 1) | (labels == 2)
            data[tissue] *= field[tissue]
        nb.Nifti1Image(data, affine).to_filename(out / f'{quantity}.nii.gz')
        _write_json(out / f'{quantity}.json', {'Units': units})

    nb.Nifti1Image(labels, affine).to_filename(out / 'dseg.nii.gz')
    _write_json(
        out / 'dseg.json',
        {
            'Units': 'label indices',
            'LabelMap': {str(k): v['name'] for k, v in params['tissues'].items()},
        },
    )
    _write_json(out / 'phantom.json', params['kinetics'])

    anat = out / 'anat'
    anat.mkdir()
    shutil.copyfile(paths[f'tpl-{TEMPLATE}_res-01_T1w.nii.gz'], anat / 'T1w.nii.gz')
    nb.Nifti1Image(mask.astype(np.uint8), affine).to_filename(anat / 'brainmask.nii.gz')
    for i, t in enumerate(('GM', 'WM', 'CSF')):
        nb.Nifti1Image(probs[..., i], affine).to_filename(anat / f'probseg-{t}.nii.gz')


def _crop_phantom(base_dir, ranges, out):
    """Crop every image of a phantom by voxel ranges ``x0:x1,y0:y1,z0:z1``, keeping world space."""
    import nibabel as nb
    import numpy as np

    bounds = [tuple(int(v) for v in r.split(':')) for r in ranges.split(',')]
    if len(bounds) != 3 or any(b <= a for a, b in bounds):
        raise ValueError(f'bad crop {ranges!r}: expected x0:x1,y0:y1,z0:z1 with x0 < x1')
    slices = tuple(slice(a, b) for a, b in bounds)
    for src in sorted(base_dir.rglob('*')):
        rel = src.relative_to(base_dir)
        dest = out / rel
        if src.is_dir():
            dest.mkdir(parents=True, exist_ok=True)
        elif src.name.endswith('.nii.gz'):
            img = nb.load(src)
            data = np.asanyarray(img.dataobj)[slices]
            affine = img.affine.copy()
            affine[:3, 3] = img.affine[:3, :3] @ [a for a, _ in bounds] + img.affine[:3, 3]
            new = nb.Nifti1Image(data, affine, img.header)
            new.set_qform(affine, code=1)
            new.set_sform(affine, code=1)
            new.to_filename(dest)
        elif src.name != 'provenance.json':
            shutil.copyfile(src, dest)


def sanitize_maps(maps, dseg):
    """Make measured maps satisfy aslscan's phantom contract; return (maps, changes).

    For future real-subject phantoms (Section 4.2 of the spec). ``maps`` holds arrays named as
    in :data:`PHANTOM_MAPS` (plus optional ``abv``/``aatt``); ``dseg`` > 0 is foreground.
    """
    import numpy as np

    maps = {k: np.array(v, dtype=np.float32) for k, v in maps.items()}
    fg = np.asarray(dseg) > 0
    changes = {}

    def record(key, count):
        if count:
            changes[key] = int(count)

    record('M0map zeroed outside the segmentation', np.count_nonzero(maps['M0map'][~fg]))
    maps['M0map'][~fg] = 0
    for name, floor in (('T1map', 0.05), ('T2map', 0.005), ('T2starmap', 0.004), ('M0map', 1e-3)):
        low = fg & ~(maps[name] >= floor)  # also catches NaN
        record(f'{name} raised to {floor} in foreground', np.count_nonzero(low))
        maps[name][low] = floor
    ceiling = 0.95 * maps['T2map']
    high = fg & (maps['T2starmap'] > ceiling)
    record('T2starmap clipped to 0.95 x T2map', np.count_nonzero(high))
    maps['T2starmap'][high] = ceiling[high]
    unperfused = fg & ~(maps['perfusion'] > 0)
    record('perfusion set to 0 where not positive', np.count_nonzero(unperfused))
    maps['perfusion'][unperfused] = 0
    record(
        'att set to 1000 where unperfused',
        np.count_nonzero(unperfused & (maps['att'] != 1000)),
    )
    maps['att'][unperfused] = 1000.0
    return maps, changes


def check_phantom_contract(phantom_dir):
    """Raise :class:`PhantomContractError` if aslscan's loader would refuse the phantom."""
    import nibabel as nb
    import numpy as np

    phantom_dir = Path(phantom_dir)
    errors = []
    dseg_img = nb.load(phantom_dir / 'dseg.nii.gz')
    dseg = np.asanyarray(dseg_img.dataobj)
    dseg_side = json.loads((phantom_dir / 'dseg.json').read_text())
    if dseg_side.get('Units') != 'label indices':
        errors.append('dseg.json Units must be "label indices"')
    if not isinstance(dseg_side.get('LabelMap'), dict):
        errors.append('dseg.json needs a LabelMap')
    if not np.all(np.equal(np.mod(dseg, 1), 0)) or dseg.min() < 0 or dseg.max() > 32767:
        errors.append('dseg must hold integers in 0..32767')
    fg = dseg > 0
    data = {}
    for name, units in {**PHANTOM_MAPS, **OPTIONAL_PHANTOM_MAPS}.items():
        img_path = phantom_dir / f'{name}.nii.gz'
        if not img_path.exists():
            if name in PHANTOM_MAPS:
                errors.append(f'{name}.nii.gz is missing')
            continue
        side = json.loads((phantom_dir / f'{name}.json').read_text())
        if side.get('Units') != units:
            errors.append(f'{name}.json Units is {side.get("Units")!r}, expected {units!r}')
        img = nb.load(img_path)
        if img.shape != dseg.shape or not np.allclose(img.affine, dseg_img.affine):
            errors.append(f'{name} is not on the dseg grid')
            continue
        data[name] = np.asanyarray(img.dataobj, dtype=np.float64)
        if not np.all(np.isfinite(data[name])):
            errors.append(f'{name} has non-finite values')
    errors.extend(
        f'{name} must be positive in the foreground'
        for name in ('T1map', 'T2map', 'T2starmap', 'M0map')
        if name in data and np.any(data[name][fg] <= 0)
    )
    if 'M0map' in data and np.any(data['M0map'][~fg] != 0):
        errors.append('M0map must be zero in the background')
    if {'T2map', 'T2starmap'} <= data.keys() and np.any(
        data['T2starmap'][fg] >= data['T2map'][fg]
    ):
        errors.append('T2starmap must be below T2map in the foreground')
    if errors:
        raise PhantomContractError(f'{phantom_dir}: ' + '; '.join(errors))


def build_phantom(name, data_dir):
    """Build (or reuse) a phantom under ``<data_dir>/aslscan/_phantoms`` and return its path."""
    out = _phantom_dir(name, data_dir)
    digest = phantom_digest(name)
    provenance = out / 'provenance.json'
    if provenance.exists() and json.loads(provenance.read_text()).get('digest') == digest:
        return out

    if name.startswith('subject:'):
        raise NotImplementedError(
            'real-subject phantoms are specified (Section 4.2 of the design spec) but not yet '
            'implemented; sanitize_maps() is the first piece'
        )

    tmp = out.with_name(f'.tmp-{out.name}-{os.getpid()}')
    shutil.rmtree(tmp, ignore_errors=True)
    tmp.mkdir(parents=True)
    if name.startswith('crop:'):
        _, base, ranges = name.split(':', 2)
        _crop_phantom(build_phantom(base, data_dir), ranges, tmp)
        source = {'crop': ranges, 'base': base}
    else:
        params = PHANTOM_PARAMS[name]
        _build_templateflow_phantom(params, tmp)
        source = {'templateflow': [t[1] for t in TEMPLATES]}
    check_phantom_contract(tmp)
    _write_json(tmp / 'provenance.json', {'name': name, 'digest': digest, 'source': source})
    if out.exists():
        shutil.rmtree(out)
    tmp.rename(out)
    return out


# ---------------------------------------------------------------------------------------------
# Recipes
# ---------------------------------------------------------------------------------------------
class RecipeError(ValueError):
    """A recipe's files are inconsistent or would be refused by aslscan."""


class FixtureUnavailable(RuntimeError):
    """A fixture is missing or stale and cannot be (or must not be) generated here."""


#: recipe.toml keys and defaults (Section 4.3 of the spec). ``acq`` is required.
RECIPE_DEFAULTS = {
    'phantom': 'tfmni',
    'acq': None,
    'anat': 'derivatives',
    'anat_offset': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    'keep_labeling_efficiency': True,
    'm0_divisor': 1.0,
    'snr_per_pair': 0.0,
    't2_mode': 'auto',
}
ANAT_MODES = ('derivatives', 'raw', 'none')
T2_MODES = ('auto', 'class', 'voxel')

#: Sidecar fields ASLPrep reads per volume (aslprep/interfaces/cbf.py, ExtractCBF).
VOLUME_WISE_FIELDS = (
    'PostLabelingDelay',
    'VascularCrushingVENC',
    'LabelingDuration',
    'EchoTime',
    'FlipAngle',
    'RepetitionTimePreparation',
)

#: Reference noise variance for the empirical SNR calibration (noise scales with its root).
_REFERENCE_NOISE_VARIANCE = 1.0


class Recipe:
    """A recipe's inputs: ``asl.json``, ``aslcontext.tsv``, ``overlay.toml``, ``recipe.toml``."""

    def __init__(self, name):
        self.name = name
        self.dir = RECIPES_DIR / name
        if not self.dir.is_dir():
            raise RecipeError(f'no recipe directory {self.dir}')
        for required in ('asl.json', 'aslcontext.tsv', 'overlay.toml', 'recipe.toml'):
            if not (self.dir / required).is_file():
                raise RecipeError(f'{name}: {required} is missing')
        settings = tomllib.loads((self.dir / 'recipe.toml').read_text())
        unknown = set(settings) - set(RECIPE_DEFAULTS)
        if unknown:
            raise RecipeError(f'{name}: unknown recipe.toml keys {sorted(unknown)}')
        self.settings = {**RECIPE_DEFAULTS, **settings}
        if not self.settings['acq'] or not re.fullmatch(r'[A-Za-z0-9]+', self.settings['acq']):
            raise RecipeError(f'{name}: acq must be a non-empty alphanumeric BIDS label')
        if self.settings['anat'] not in ANAT_MODES:
            raise RecipeError(f'{name}: anat must be one of {ANAT_MODES}')
        if self.settings['t2_mode'] not in T2_MODES:
            raise RecipeError(f'{name}: t2_mode must be one of {T2_MODES}')
        if len(self.settings['anat_offset']) != 6:
            raise RecipeError(f'{name}: anat_offset needs six values (tx ty tz rx ry rz)')
        if self.settings['m0_divisor'] <= 0 or self.settings['snr_per_pair'] < 0:
            raise RecipeError(f'{name}: m0_divisor must be > 0 and snr_per_pair >= 0')
        self.sidecar = json.loads((self.dir / 'asl.json').read_text())
        rows = (self.dir / 'aslcontext.tsv').read_text().split()
        if not rows or rows[0] != 'volume_type':
            raise RecipeError(f'{name}: aslcontext.tsv must start with a volume_type header')
        self.context = rows[1:]
        self.overlay_text = (self.dir / 'overlay.toml').read_text()
        self.overlay = tomllib.loads(self.overlay_text)

    def __getattr__(self, key):
        settings = self.__dict__.get('settings', {})
        if key in settings:
            return settings[key]
        raise AttributeError(key)

    @property
    def digest(self):
        return _digest_dir(self.dir)


def load_recipe(name):
    if name not in RECIPES:
        raise RecipeError(f'unknown recipe {name!r}; known: {sorted(RECIPES)}')
    return Recipe(name)


def _phantom_grid(phantom_dir):
    import nibabel as nb

    img = nb.load(Path(phantom_dir) / 'dseg.nii.gz')
    return img.affine, img.shape


def expected_slices(extent_mm, voxel_mm):
    """aslscan's slice count along an axis: ``max(1, ceil(extent / voxel - 1e-9))``.

    From ``acquisition_grid`` in aslscan's ``src/resample.rs``.
    """
    return max(1, math.ceil(extent_mm / voxel_mm - 1e-9))


def check_recipe(recipe, phantom_dir):
    """Refuse a recipe aslscan or ASLPrep would reject, before running anything."""
    errors = []
    side, n = recipe.sidecar, len(recipe.context)
    errors.extend(
        f'{field} has {len(side[field])} values but aslcontext has {n} rows'
        for field in VOLUME_WISE_FIELDS
        if isinstance(side.get(field), list) and len(side[field]) != n
    )
    noise = recipe.overlay.get('acquisition', {}).get('noise_variance')
    if noise is None:
        errors.append('overlay.toml must set [acquisition] noise_variance')
    elif recipe.snr_per_pair and noise != 0:
        errors.append('with snr_per_pair, overlay.toml noise_variance must be 0 (it is derived)')
    if 'seed' not in recipe.overlay:
        errors.append('overlay.toml must set seed')
    if 'matrix' not in recipe.overlay.get('acquisition', {}):
        errors.append('overlay.toml must set [acquisition] matrix')

    affine, shape = _phantom_grid(phantom_dir)
    voxel = side.get('AcquisitionVoxelSize')
    if not voxel or len(voxel) != 3:
        errors.append('asl.json needs a three-value AcquisitionVoxelSize')
    elif side.get('MRAcquisitionType') == '3D':
        if 'SliceTiming' in side or side.get('MultibandAccelerationFactor', 1) != 1:
            errors.append('3D acquisitions must not carry SliceTiming or multiband')
    else:
        extent = shape[2] * abs(affine[2, 2])
        n_slices = expected_slices(extent, voxel[2])
        timing = side.get('SliceTiming', [])
        if len(timing) != n_slices:
            errors.append(
                f'SliceTiming has {len(timing)} entries; the phantom extent {extent:g} mm at '
                f'{voxel[2]:g} mm slices gives {n_slices} slices'
            )
        mb = side.get('MultibandAccelerationFactor', 1)
        if mb > 1 and len(timing) == n_slices:
            if n_slices % mb:
                errors.append(f'{n_slices} slices are not a multiple of multiband factor {mb}')
            else:
                groups = n_slices // mb
                if any(timing[i] != timing[i % groups] for i in range(n_slices)):
                    errors.append(
                        f'multiband {mb}: slices g, g + {groups}, ... must share a slice time'
                    )
                if len(set(timing[:groups])) != groups:
                    errors.append(f'multiband {mb}: the {groups} slice groups need distinct times')
    if recipe.m0_divisor != 1 and side.get('M0Type') == 'Absent':
        errors.append('m0_divisor needs an M0 image (M0Type is Absent)')
    if errors:
        raise RecipeError(f'{recipe.name}: ' + '; '.join(errors))


# ---------------------------------------------------------------------------------------------
# Generation
# ---------------------------------------------------------------------------------------------
@contextlib.contextmanager
def _generation_lock(data_dir):
    import fcntl  # POSIX only: generation is documented as Linux/WSL only

    root = Path(data_dir) / 'aslscan'
    root.mkdir(parents=True, exist_ok=True)
    with open(root / '.lock', 'w') as handle:
        fcntl.flock(handle, fcntl.LOCK_EX)
        try:
            yield
        finally:
            fcntl.flock(handle, fcntl.LOCK_UN)


def _set_noise(overlay_text, variance):
    """Replace the overlay's ``noise_variance`` (which :func:`check_recipe` requires)."""
    new, count = re.subn(
        r'(?m)^(\s*noise_variance\s*=\s*)[^\s#]+', rf'\g<1>{variance!r}', overlay_text
    )
    if count != 1:
        raise RecipeError('overlay.toml must contain exactly one noise_variance line')
    return new


def run_aslscan(binary, workdir, phantom_dir, out_dir, threads=4, t2_mode='auto'):
    """Run aslscan on the recipe files copied into ``workdir``."""
    out_dir = Path(out_dir)
    shutil.rmtree(out_dir, ignore_errors=True)
    env = {**os.environ, 'RAYON_NUM_THREADS': str(threads)}
    cmd = [
        str(binary),
        '--asl-json',
        str(workdir / 'asl.json'),
        '--aslcontext',
        str(workdir / 'aslcontext.tsv'),
        '--overlay',
        str(workdir / 'overlay.toml'),
        '--phantom',
        str(phantom_dir),
        '--out',
        str(out_dir),
        '--sub',
        '01',
        '--t2-mode',
        t2_mode,
    ]
    proc = subprocess.run(cmd, env=env, capture_output=True, text=True, check=False)
    if proc.returncode:
        raise RuntimeError(f'aslscan failed ({proc.returncode}):\n{proc.stderr}{proc.stdout}')
    return out_dir


def _raw_paths(raw):
    perf = Path(raw) / 'sub-01' / 'perf'
    return {
        'asl': perf / 'sub-01_part-mag_asl.nii.gz',
        'asl_json': perf / 'sub-01_part-mag_asl.json',
        'context': perf / 'sub-01_aslcontext.tsv',
        'm0': perf / 'sub-01_m0scan.nii.gz',
        'm0_json': perf / 'sub-01_m0scan.json',
        'truth': perf / 'ground-truth',
    }


def deltam_estimates(asl, context):
    """Delta-M estimates as ASLPrep forms them: control - label by order, plus deltam rows.

    Returns an array with the estimates on the last axis.
    """
    import numpy as np

    control = [i for i, t in enumerate(context) if t == 'control']
    label = [i for i, t in enumerate(context) if t == 'label']
    deltam = [i for i, t in enumerate(context) if t == 'deltam']
    parts = []
    if label:
        parts.append(asl[..., control] - asl[..., label])
    if deltam:
        parts.append(asl[..., deltam])
    return np.concatenate(parts, axis=-1)


def _pv_fractions(phantom_dir, acq_img):
    import nibabel as nb

    from aslprep.tests import truth_geometry as tg

    dseg = nb.load(Path(phantom_dir) / 'dseg.nii.gz')
    return tg.overlap_fractions(
        dseg.get_fdata(), dseg.affine, acq_img.affine, acq_img.shape[:3], label_values=(1, 2, 3)
    )


def _snr(raw_noisy, raw_clean, context, gm_mask):
    """Delta-M SNR per estimate in ``gm_mask``: mean clean delta-M over the noise SD."""
    import nibabel as nb
    import numpy as np

    noisy = deltam_estimates(nb.load(_raw_paths(raw_noisy)['asl']).get_fdata(), context)
    clean = deltam_estimates(nb.load(_raw_paths(raw_clean)['asl']).get_fdata(), context)
    signal = float(np.mean(clean[gm_mask]))
    noise = float(np.std((noisy - clean)[gm_mask]))
    return signal, noise


def _calibrate_noise(recipe, binary, work, phantom_dir, build, threads):
    """Empirical noise calibration (Section 5 of the spec). Returns (raw dir, noise record)."""
    import nibabel as nb

    clean = run_aslscan(binary, work, phantom_dir, build / 'clean', threads, recipe.t2_mode)
    if not recipe.snr_per_pair:
        return clean, {'snr_per_pair': 0.0, 'noise_variance': 0.0}

    pv = _pv_fractions(phantom_dir, nb.load(_raw_paths(clean)['asl']))
    gm = (pv[1] >= 0.7) & (pv[3] < 0.5)
    if gm.sum() < 50:
        raise RecipeError(f'{recipe.name}: too few GM-dominant voxels to calibrate noise')

    (work / 'overlay.toml').write_text(_set_noise(recipe.overlay_text, _REFERENCE_NOISE_VARIANCE))
    ref = run_aslscan(binary, work, phantom_dir, build / 'reference', threads, recipe.t2_mode)
    signal, noise0 = _snr(ref, clean, recipe.context, gm)
    variance = _REFERENCE_NOISE_VARIANCE * (signal / (recipe.snr_per_pair * noise0)) ** 2

    (work / 'overlay.toml').write_text(_set_noise(recipe.overlay_text, variance))
    final = run_aslscan(binary, work, phantom_dir, build / 'final', threads, recipe.t2_mode)
    signal, noise = _snr(final, clean, recipe.context, gm)
    achieved = signal / noise
    if abs(achieved / recipe.snr_per_pair - 1) > 0.1:
        raise RuntimeError(
            f'{recipe.name}: achieved delta-M SNR {achieved:.2f}, target {recipe.snr_per_pair}'
        )
    return final, {
        'snr_per_pair': recipe.snr_per_pair,
        'noise_variance': variance,
        'achieved_snr_per_pair': achieved,
        'gm_deltam': signal,
    }


def _save_like(img, data, path, affine=None):
    """Save ``data`` with ``img``'s header (and optionally a new affine, set in qform and sform)."""
    import nibabel as nb

    affine = img.affine if affine is None else affine
    new = nb.Nifti1Image(data, affine, img.header)
    new.set_qform(affine, code=1)
    new.set_sform(affine, code=1)
    new.to_filename(path)


def _assemble(recipe, raw, phantom_dir, out, noise, stamp):
    """Turn aslscan's output into the fixture's BIDS dataset (Section 4.4 of the spec)."""
    import nibabel as nb
    import numpy as np

    from aslprep.tests import truth_geometry as tg

    src = _raw_paths(raw)
    acq = recipe.acq
    perf = out / 'sub-01' / 'perf'
    perf.mkdir(parents=True)
    stem = f'sub-01_acq-{acq}'
    asl_rel = f'sub-01/perf/{stem}_asl.nii.gz'

    sidecar = json.loads(src['asl_json'].read_text())
    resolved = sidecar.get('AslscanSimulation', {}).get('Resolved', {})
    le_source = resolved.get('LabelingEfficiency', {}).get('Source')
    if not recipe.keep_labeling_efficiency and le_source == 'Default':
        sidecar.pop('LabelingEfficiency', None)
    divisor = float(recipe.m0_divisor)
    m0_type = sidecar.get('M0Type')
    if m0_type == 'Estimate' and divisor != 1:
        sidecar['M0Estimate'] = sidecar['M0Estimate'] / divisor
    _write_json(perf / f'{stem}_asl.json', sidecar)

    asl_img = nb.load(src['asl'])
    asl = asl_img.get_fdata(dtype=np.float32)
    if m0_type == 'Included' and divisor != 1:
        m0_rows = [i for i, t in enumerate(recipe.context) if t == 'm0scan']
        asl[..., m0_rows] /= divisor
    _save_like(asl_img, asl, perf / f'{stem}_asl.nii.gz')
    shutil.copyfile(src['context'], perf / f'{stem}_aslcontext.tsv')

    if src['m0'].exists():
        m0_img = nb.load(src['m0'])
        _save_like(
            m0_img, m0_img.get_fdata(dtype=np.float32) / divisor, perf / f'{stem}_m0scan.nii.gz'
        )
        m0_side = json.loads(src['m0_json'].read_text())
        m0_side['IntendedFor'] = [f'bids::{asl_rel}']
        _write_json(perf / f'{stem}_m0scan.json', m0_side)

    truth = perf / 'ground-truth'
    shutil.copytree(src['truth'], truth)
    pv = _pv_fractions(phantom_dir, asl_img)
    for value, tissue in ((1, 'GM'), (2, 'WM'), (3, 'CSF')):
        _save_like(
            asl_img.slicer[..., 0],
            pv[value].astype(np.float32),
            truth / f'sub-01_desc-pv{tissue}_gt.nii.gz',
        )
    _write_json(truth / 'simulation.json', sidecar.get('AslscanSimulation', {}))

    r = tg.rigid_ras(*recipe.anat_offset)
    provenance = json.loads((Path(phantom_dir) / 'provenance.json').read_text())
    if recipe.anat != 'none':
        _write_anatomy(phantom_dir, out, r, recipe.anat == 'derivatives')

    _write_json(
        truth / 'truth.json',
        {
            'recipe': recipe.name,
            'recipe_settings': recipe.settings,
            'phantom': provenance['name'],
            'phantom_digest': provenance['digest'],
            'anat_offset': recipe.anat_offset,
            'R': r.tolist(),
            'motion_center': tg.fov_center(asl_img.affine, asl_img.shape[:3]).tolist(),
            'noise': noise,
            'm0_divisor': divisor,
            'aslscan': stamp,
            'spec_digest': spec_digest(),
        },
    )
    _write_json(
        out / 'dataset_description.json',
        {
            'Name': f'aslscan fixture {recipe.name}',
            'BIDSVersion': '1.10.0',
            'DatasetType': 'raw',
            'GeneratedBy': [
                {'Name': 'aslscan', 'Version': ASLSCAN_REF, 'CodeURL': ASLSCAN_REPO},
                {'Name': 'mrsim-acq', 'Version': MRSIM_ACQ_REF, 'CodeURL': MRSIM_ACQ_REPO},
                {
                    'Name': 'aslprep.tests.aslscan_fixtures',
                    'Description': f'recipe {recipe.name} on phantom {provenance["name"]}',
                },
            ],
        },
    )
    (out / 'README').write_text(
        f'Simulated ASL data for ASLPrep tests (recipe {recipe.name}).\n'
        'Ground truth is in sub-01/perf/ground-truth/.\n'
    )
    (out / '.bidsignore').write_text('**/ground-truth\n**/ground-truth/**\n')


def _write_anatomy(phantom_dir, out, r, derivatives):
    """The T1w (affine ``R @ A``) and, optionally, smriprep-style derivatives with transforms."""
    import nibabel as nb
    import numpy as np

    from aslprep.tests import truth_geometry as tg

    ph = Path(phantom_dir)
    anat = out / 'sub-01' / 'anat'
    anat.mkdir(parents=True)
    t1w = nb.load(ph / 'anat' / 'T1w.nii.gz')
    new_affine = r @ t1w.affine
    _save_like(t1w, np.asanyarray(t1w.dataobj), anat / 'sub-01_T1w.nii.gz', new_affine)
    _write_json(anat / 'sub-01_T1w.json', {'Description': 'phantom anatomy (TemplateFlow T1w)'})
    if not derivatives:
        return

    deriv = out / 'derivatives' / 'anat'
    danat = deriv / 'sub-01' / 'anat'
    danat.mkdir(parents=True)
    _write_json(
        deriv / 'dataset_description.json',
        {
            'Name': 'phantom anatomical derivatives',
            'BIDSVersion': '1.10.0',
            'DatasetType': 'derivative',
            'GeneratedBy': [{'Name': 'aslprep.tests.aslscan_fixtures'}],
        },
    )
    _save_like(
        t1w, np.asanyarray(t1w.dataobj), danat / 'sub-01_desc-preproc_T1w.nii.gz', new_affine
    )
    for src, dest in (
        ('anat/brainmask.nii.gz', 'sub-01_desc-brain_mask.nii.gz'),
        ('dseg.nii.gz', 'sub-01_dseg.nii.gz'),
        ('anat/probseg-GM.nii.gz', 'sub-01_label-GM_probseg.nii.gz'),
        ('anat/probseg-WM.nii.gz', 'sub-01_label-WM_probseg.nii.gz'),
        ('anat/probseg-CSF.nii.gz', 'sub-01_label-CSF_probseg.nii.gz'),
    ):
        img = nb.load(ph / src)
        _save_like(img, np.asanyarray(img.dataobj), danat / dest, new_affine)
    # Pull mappings: from-T1w_to-MNI sends an MNI (= phantom) point p to its T1w point R p.
    tg.write_itk_affine(danat / f'sub-01_from-T1w_to-{TEMPLATE}_mode-image_xfm.txt', r)
    tg.write_itk_affine(
        danat / f'sub-01_from-{TEMPLATE}_to-T1w_mode-image_xfm.txt', np.linalg.inv(r)
    )


def _file_hashes(root):
    return {
        p.relative_to(root).as_posix(): _sha256_file(p)
        for p in sorted(Path(root).rglob('*'))
        if p.is_file() and p.name != 'manifest.json'
    }


def generate(name, data_dir, binary, threads=4):
    """Generate one fixture into ``<data_dir>/aslscan/<name>`` and return its path."""
    binary = check_aslscan(binary)
    recipe = load_recipe(name)
    root = Path(data_dir) / 'aslscan'
    with _generation_lock(data_dir):
        phantom_dir = build_phantom(recipe.phantom, data_dir)
        check_recipe(recipe, phantom_dir)
        tmp = root / f'.tmp-{name}-{os.getpid()}'
        shutil.rmtree(tmp, ignore_errors=True)
        build = tmp.with_name(tmp.name + '-build')
        shutil.rmtree(build, ignore_errors=True)
        work = build / 'work'
        shutil.copytree(recipe.dir, work)
        stamp = json.loads((binary.parent / STAMP_NAME).read_text())
        try:
            raw, noise = _calibrate_noise(recipe, binary, work, phantom_dir, build, threads)
            tmp.mkdir(parents=True)
            _assemble(recipe, raw, phantom_dir, tmp, noise, stamp)
            _write_json(
                tmp / 'manifest.json',
                {
                    'recipe': name,
                    'spec_digest': spec_digest(),
                    'recipe_digest': recipe.digest,
                    'phantom_digest': phantom_digest(recipe.phantom),
                    'aslscan': stamp,
                    'files': _file_hashes(tmp),
                },
            )
            out = root / name
            old = root / f'.old-{name}-{os.getpid()}'
            if out.exists():
                out.rename(old)
            tmp.rename(out)
            shutil.rmtree(old, ignore_errors=True)
        finally:
            shutil.rmtree(build, ignore_errors=True)
            shutil.rmtree(tmp, ignore_errors=True)
    return out


def _manifest_problem(fixture, check_hashes):
    manifest_file = fixture / 'manifest.json'
    if not manifest_file.is_file():
        return 'missing'
    manifest = json.loads(manifest_file.read_text())
    if manifest.get('spec_digest') != spec_digest():
        return 'stale (spec digest differs)'
    if check_hashes and manifest.get('files') != _file_hashes(fixture):
        return 'files differ from their manifest'
    return None


def verify(data_dir, names=None, check_hashes=True):
    """Return ``{recipe: problem}`` for fixtures that are missing, stale or modified."""
    root = Path(data_dir) / 'aslscan'
    problems = {}
    for name in names or sorted(RECIPES):
        problem = _manifest_problem(root / name, check_hashes)
        if problem:
            problems[name] = problem
    return problems


def default_data_dir():
    return TESTS_DIR / 'test_data'


def fixture_dir(name, data_dir=None):
    """Path of a current fixture, generating it here when allowed (Section 4.5 of the spec)."""
    data_dir = Path(data_dir) if data_dir else default_data_dir()
    path = data_dir / 'aslscan' / name
    problem = _manifest_problem(path, check_hashes=False)
    if problem is None:
        return path
    if os.environ.get('ASLPREP_REQUIRE_FIXTURES') == '1':
        raise FixtureUnavailable(
            f'aslscan fixture {name} is {problem} under {data_dir}, and '
            'ASLPREP_REQUIRE_FIXTURES=1 forbids generating it here'
        )
    try:
        binary = find_aslscan()
    except AslscanUnavailable as exc:
        raise FixtureUnavailable(f'aslscan fixture {name} is {problem}: {exc}') from exc
    return generate(name, data_dir, binary)


def mask_populations(fixture):
    """Voxel counts of the scoring masks of spec Section 4.7 (``valid``, ``dom_GM``, ``dom_WM``).

    Uses the truth only: ``valid`` = brain (PV sum >= 0.5) without CSF-dominant voxels and with
    perfusion above 5 ml/100g/min; ``dom_L`` = ``valid`` & PV_L >= 0.7.
    """
    import nibabel as nb

    gt = Path(fixture) / 'sub-01' / 'perf' / 'ground-truth'
    pv = {t: nb.load(gt / f'sub-01_desc-pv{t}_gt.nii.gz').get_fdata() for t in ('GM', 'WM', 'CSF')}
    perf = nb.load(gt / 'sub-01_desc-perfusion_gt.nii.gz').get_fdata()
    valid = (pv['GM'] + pv['WM'] + pv['CSF'] >= 0.5) & (pv['CSF'] < 0.5) & (perf > 5)
    return {
        'valid': int(valid.sum()),
        'dom_GM': int((valid & (pv['GM'] >= 0.7)).sum()),
        'dom_WM': int((valid & (pv['WM'] >= 0.7)).sum()),
        'grid': int(perf.size),
    }


def check_threads(name, binary):
    """Run aslscan on a recipe with 1 and 4 threads (with noise) and compare the images."""
    import tempfile

    import nibabel as nb
    import numpy as np

    binary = check_aslscan(binary)
    recipe = load_recipe(name)
    with tempfile.TemporaryDirectory() as tmp:
        tmp = Path(tmp)
        phantom_dir = build_phantom(recipe.phantom, tmp)
        work = tmp / 'work'
        shutil.copytree(recipe.dir, work)
        (work / 'overlay.toml').write_text(
            _set_noise(recipe.overlay_text, _REFERENCE_NOISE_VARIANCE)
        )
        runs = {
            n: run_aslscan(binary, work, phantom_dir, tmp / f'threads-{n}', n, recipe.t2_mode)
            for n in (1, 4)
        }
        images = sorted(runs[1].rglob('*.nii.gz'))
        differing = []
        for img in images:
            rel = img.relative_to(runs[1])
            a = np.asanyarray(nb.load(img).dataobj)
            b = np.asanyarray(nb.load(runs[4] / rel).dataobj)
            if a.shape != b.shape or not np.array_equal(a, b):
                differing.append(rel.as_posix())
    if not images:
        raise RuntimeError(f'{name}: aslscan wrote no images')
    if differing:
        raise RuntimeError(f'{name}: outputs differ between 1 and 4 threads: {differing}')
    return f'{name}: {len(images)} images identical at 1 and 4 threads'


# ---------------------------------------------------------------------------------------------
# Command line
# ---------------------------------------------------------------------------------------------
def _get_parser():
    parser = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    parser.add_argument('--spec', action='store_true', help='print the spec file and exit')
    parser.add_argument(
        '--build-aslscan',
        metavar='WORKDIR',
        type=Path,
        help='build aslscan at the pinned revisions in WORKDIR and print its path',
    )
    parser.add_argument(
        '--generate', metavar='DATA_DIR', type=Path, help='generate fixtures into DATA_DIR'
    )
    parser.add_argument(
        '--verify',
        metavar='DATA_DIR',
        type=Path,
        help='check every fixture in DATA_DIR against the spec digest and its manifest',
    )
    parser.add_argument(
        '--check-threads',
        metavar='RECIPE',
        help='check that aslscan output for RECIPE is identical at 1 and 4 threads',
    )
    parser.add_argument(
        '--masks', metavar='DATA_DIR', type=Path, help='print scoring-mask voxel counts'
    )
    parser.add_argument('--aslscan', type=Path, help='the aslscan binary (stamped)')
    parser.add_argument('--only', nargs='+', metavar='RECIPE', help='restrict --generate')
    parser.add_argument('--threads', type=int, default=4, help='aslscan threads (default 4)')
    return parser


def main(argv=None):
    parser = _get_parser()
    opts = parser.parse_args(argv)
    if opts.spec:
        sys.stdout.write(spec_text())
        return 0
    if opts.build_aslscan:
        print(build_aslscan(opts.build_aslscan))
        return 0
    if opts.generate:
        binary = find_aslscan(opts.aslscan)
        for name in opts.only or sorted(RECIPES):
            print(f'{name}: {generate(name, opts.generate, binary, opts.threads)}', flush=True)
        return 0
    if opts.verify:
        problems = verify(opts.verify)
        for name, problem in problems.items():
            print(f'{name}: {problem}')
        print(f'{len(RECIPES) - len(problems)}/{len(RECIPES)} fixtures current')
        return 1 if problems else 0
    if opts.masks:
        for name in opts.only or sorted(RECIPES):
            print(f'{name}: {mask_populations(Path(opts.masks) / "aslscan" / name)}')
        return 0
    if opts.check_threads:
        print(check_threads(opts.check_threads, find_aslscan(opts.aslscan)))
        return 0
    parser.print_help()
    return 1


if __name__ == '__main__':
    sys.exit(main())
