"""Simulated ASL fixtures with ground truth, generated by aslscan.

This module is the registry for the ground-truth test datasets described in
``docs/specs/2026-10-08-aslscan-ground-truth-tests-design.md``.
It pins the simulator and every input,
renders the spec file that keys the CircleCI cache (``.circleci/aslscan_fixtures.txt``),
and generates, verifies and locates the fixtures.

It must import with the standard library alone,
so that ``python -m aslprep.tests.aslscan_fixtures --spec`` runs anywhere.
Third-party imports live inside the functions that need them.

Usage::

    python -m aslprep.tests.aslscan_fixtures --spec > .circleci/aslscan_fixtures.txt
"""

import argparse
import hashlib
import json
import sys
from pathlib import Path

#: Bump to discard a bad CircleCI cache entry (caches are immutable).
CACHE_EPOCH = 1

ASLSCAN_REPO = 'https://github.com/PennLINC/aslscan.git'
ASLSCAN_REF = '82919454d11ee63a1bc8032e4a362f9b745e5d97'
MRSIM_ACQ_REPO = 'https://github.com/PennLINC/mrsim-acq.git'
MRSIM_ACQ_REF = 'e64caff8b18358704ef876b5a16a344192b3a014'
RUST_TOOLCHAIN = '1.98.0'
CARGO_FEATURES = 'cli,kspace,par'

#: Python requirements of the fixture generator (CI installs these into a venv).
PY_REQUIREMENTS = (
    'numpy==2.5.3',
    'nibabel==5.4.2',
    'scipy==1.18.1',
    'templateflow==25.1.2',
)

#: TemplateFlow files the phantoms are built from: (query, file name, SHA-256).
TEMPLATE = 'MNI152NLin2009cAsym'
TEMPLATES = (
    (
        {'resolution': 1, 'desc': None, 'suffix': 'T1w'},
        'tpl-MNI152NLin2009cAsym_res-01_T1w.nii.gz',
        '1f27aabea9f7183dc0c69dafa71e1787b921ca778d655d9c1bf302b273d5627a',
    ),
    (
        {'resolution': 1, 'desc': 'brain', 'suffix': 'mask'},
        'tpl-MNI152NLin2009cAsym_res-01_desc-brain_mask.nii.gz',
        'e40bb1816736504d4c25abc243c1c8503df1d308f64c048318aa4b829e09a7ae',
    ),
    (
        {'resolution': 1, 'label': 'GM', 'suffix': 'probseg'},
        'tpl-MNI152NLin2009cAsym_res-01_label-GM_probseg.nii.gz',
        '662b18e83dddc554b19c621d9750af3454b54d4e103df03633eacced3884805a',
    ),
    (
        {'resolution': 1, 'label': 'WM', 'suffix': 'probseg'},
        'tpl-MNI152NLin2009cAsym_res-01_label-WM_probseg.nii.gz',
        'b2f80e29f5a1ef55325215d1716ef611f5b1a3cd97b4a49ef4e9564e9564e945',
    ),
    (
        {'resolution': 1, 'label': 'CSF', 'suffix': 'probseg'},
        'tpl-MNI152NLin2009cAsym_res-01_label-CSF_probseg.nii.gz',
        '8a74e36b067a3fb670f6785b94479cc3df4d219a3f72d69d57aef332e4947048',
    ),
)

#: Modules (in this directory) whose source feeds the spec digest.
HASHED_MODULES = ('aslscan_fixtures.py',)

#: Phantom name -> builder parameters (Section 4.2 of the spec).
PHANTOM_PARAMS = {}

#: Recipe name -> one-line description. Inputs live in tests/data/aslscan/<name>/.
RECIPES = {}

TESTS_DIR = Path(__file__).resolve().parent
RECIPES_DIR = TESTS_DIR / 'data' / 'aslscan'
REPO_ROOT = TESTS_DIR.parents[1]
SPEC_FILE = REPO_ROOT / '.circleci' / 'aslscan_fixtures.txt'
SPEC_COMMAND = 'python -m aslprep.tests.aslscan_fixtures --spec > .circleci/aslscan_fixtures.txt'


def _lf(data):
    """Normalize line endings so Windows and POSIX checkouts hash alike."""
    return data.replace(b'\r\n', b'\n')


def _digest_bytes(data):
    return hashlib.sha256(_lf(data)).hexdigest()


def _digest_dir(path):
    """Hash a directory's files: sorted relative path, length and LF-normalized content."""
    path = Path(path)
    sha = hashlib.sha256()
    for f in sorted(p for p in path.rglob('*') if p.is_file()):
        data = _lf(f.read_bytes())
        sha.update(f.relative_to(path).as_posix().encode())
        sha.update(b'\0')
        sha.update(str(len(data)).encode())
        sha.update(b'\0')
        sha.update(data)
    return sha.hexdigest()


def _digest_json(obj):
    return hashlib.sha256(json.dumps(obj, sort_keys=True).encode()).hexdigest()


def spec_text():
    """Render the spec file: every input that determines the fixtures, then their digest."""
    lines = [
        '# generated by python -m aslprep.tests.aslscan_fixtures --spec; do not edit',
        f'CACHE_EPOCH={CACHE_EPOCH}',
        f'ASLSCAN_REF={ASLSCAN_REF}',
        f'MRSIM_ACQ_REF={MRSIM_ACQ_REF}',
        f'RUST_TOOLCHAIN={RUST_TOOLCHAIN}',
        f'CARGO_FEATURES={CARGO_FEATURES}',
        f'PY_REQUIREMENTS={";".join(PY_REQUIREMENTS)}',
    ]
    lines += [f'TEMPLATE {name} {sha}' for _, name, sha in TEMPLATES]
    lines += [
        f'BUILDER {mod} {_digest_bytes((TESTS_DIR / mod).read_bytes())}' for mod in HASHED_MODULES
    ]
    lines += [f'PHANTOM {name} {_digest_json(p)}' for name, p in sorted(PHANTOM_PARAMS.items())]
    lines += [f'RECIPE {name} {_digest_dir(RECIPES_DIR / name)}' for name in sorted(RECIPES)]
    digest = hashlib.sha256('\n'.join(lines).encode()).hexdigest()
    return '\n'.join([*lines, f'DIGEST {digest}']) + '\n'


def spec_digest():
    """The DIGEST line of the current spec text."""
    return spec_text().rstrip('\n').rsplit(' ', 1)[1]


def _get_parser():
    parser = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    parser.add_argument('--spec', action='store_true', help='print the spec file and exit')
    return parser


def main(argv=None):
    opts = _get_parser().parse_args(argv)
    if opts.spec:
        sys.stdout.write(spec_text())
        return 0
    _get_parser().print_help()
    return 1


if __name__ == '__main__':
    sys.exit(main())
